Get your discussion fixed faster by creating a minimal reproduction.
This means a repository dedicated to reproducing this issue with the minimal dependencies and config possible.


Before we start working on your issue we need to know exactly what's causing the current behavior.
A minimal reproduction helps us with this.
Discussions without reproductions are less likely to be converted to Issues.


Please follow these steps:
 1. Read our guide on creating a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md).
 2. Go to our [minimal reproduction template repository](https://github.com/renovatebot/minimal-reproduction-template).
 3. Select the _Use this template_ button to create a new repository based on the template.
 4. Work on the minimal reproduction in your own repository.
 5. Fill out the information in your repository's `README.md`.
 6. Add the link to your reproduction to the first post of your Discussion. If you are not the original author, you can post a new comment with the link.


If you need help with installation or onboarding, please refer to our [Installing & Onboarding guide](https://docs.renovatebot.com/getting-started/installing-onboarding/).


Good luck,


The Renovate team
